CONTANT:
  REDIS_IP: 59.110.68.237
  SQL_IP: localhost
  SQLPASSWORD: 123
  SQLUSERNAME: root

spring:
  profiles:
    active: 8888
  redis:
    host: ${CONTANT.REDIS_IP}
    port: 1111
    timeout: 1000
    password: 123
    database: 15
  lettuce:
    pool:
      max-active: 20
      max-wait: -1ms
      max-idle: 10
      min-idle: 1